# Generated by Django 4.2.7 on 2024-02-29 12:34

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_wishlist_wishlist_unique_product_user_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecommerceuser',
            name='stripe_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='mobile',
            field=phone_field.models.PhoneField(blank=True, max_length=31, null=True, verbose_name='mobile'),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='telephone',
            field=phone_field.models.PhoneField(blank=True, max_length=31, null=True, verbose_name='telephone'),
        ),
    ]
