# Generated by Django 4.2.7 on 2024-03-26 20:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_ecommerceuser_stripe_id_alter_useraddress_mobile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ecommerceuser',
            name='stripe_id',
        ),
        migrations.AddField(
            model_name='useraddress',
            name='stripe_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_address', to=settings.AUTH_USER_MODEL),
        ),
    ]
