# Generated by Django 4.2.7 on 2024-01-22 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('desc', models.TextField(max_length=500, verbose_name='Description')),
                ('discount_percent', models.DecimalField(decimal_places=0, max_digits=3)),
                ('active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(auto_now_add=True, verbose_name='Modified at')),
                ('deleted_at', models.DateTimeField(default=None, null=True, verbose_name='Deleted at')),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('desc', models.TextField(max_length=500, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(auto_now_add=True, verbose_name='Modified at')),
                ('deleted_at', models.DateTimeField(default=None, null=True, verbose_name='Deleted at')),
            ],
        ),
        migrations.CreateModel(
            name='ProductInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, verbose_name='Quantity')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(auto_now_add=True, verbose_name='Modified at')),
                ('deleted_at', models.DateTimeField(default=None, null=True, verbose_name='Deleted at')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('desc', models.TextField(max_length=500, verbose_name='Description')),
                ('SKU', models.CharField(max_length=10)),
                ('price', models.FloatField(verbose_name='Price')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(auto_now_add=True, verbose_name='Modified at')),
                ('deleted_at', models.DateTimeField(default=None, null=True, verbose_name='Deleted at')),
                ('category_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.productcategory')),
                ('discount_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.discount')),
                ('inventory_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.productinventory')),
            ],
        ),
    ]
