# Generated by Django 4.2.7 on 2024-02-19 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('core', '0002_remove_discount_active_discount_is_active_and_more'), ('core', '0003_alter_discount_deleted_at_alter_discount_modified_at_and_more')]

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discount',
            name='active',
        ),
        migrations.AddField(
            model_name='discount',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='discount_percent',
            field=models.DecimalField(decimal_places=0, max_digits=3, verbose_name='discount percentage'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Deleted at'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='modified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Modified at'),
        ),
        migrations.AlterField(
            model_name='product',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Deleted at'),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product', to='core.discount'),
        ),
        migrations.AlterField(
            model_name='product',
            name='modified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Modified at'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Deleted at'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='modified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Modified at'),
        ),
        migrations.AlterField(
            model_name='productinventory',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Deleted at'),
        ),
        migrations.AlterField(
            model_name='productinventory',
            name='modified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Modified at'),
        ),
    ]
