# Generated by Django 4.2.7 on 2024-03-03 17:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shopping', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetails',
            name='status',
            field=models.CharField(choices=[('ARCHIVED', 'archived'), ('CANCELED', 'canceled'), ('FULFILLED', 'fulfilled'), ('OPEN', 'open')], default='OPEN', verbose_name='status'),
        ),
        migrations.AddField(
            model_name='orderdetails',
            name='total',
            field=models.DecimalField(decimal_places=2, default=3, max_digits=6, verbose_name='total'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderdetails',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='orderdetails',
            name='modified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Modified at'),
        ),
        migrations.AlterField(
            model_name='orderdetails',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='modified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Modified at'),
        ),
    ]
