# Generated by Django 4.2.7 on 2024-02-05 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppingsession',
            name='total',
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='shopping.shoppingsession'),
        ),
    ]
