# Generated by Django 4.2.7 on 2024-03-03 18:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0002_orderdetails_status_orderdetails_total_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(blank=True, null=True, verbose_name='Modified at')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('currency', models.CharField(choices=[('EUR', 'eur'), ('PLN', 'pln'), ('USD', 'usd')], max_length=100)),
                ('status', models.CharField(choices=[('CANCELED', 'canceled'), ('FAILED', 'failed'), ('PENDING', 'pending'), ('SUCCEEDED', 'succeeded')], default='PENDING', max_length=100)),
                ('method', models.CharField(choices=[('BLIK', 'blik'), ('CARD', 'card')], max_length=100)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='payment', to='shopping.orderdetails')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
