# Generated by Django 4.2.7 on 2024-02-25 15:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0002_orderdetails_is_active_orderdetails_total_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetails',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='is active'),
        ),
        migrations.AlterField(
            model_name='orderdetails',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='total'),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(blank=True, null=True, verbose_name='Modified at')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('currency', models.CharField(choices=[('EUR', 'eur'), ('PLN', 'pln'), ('USD', 'usd')], max_length=100)),
                ('status', models.CharField(choices=[('DECLINED', 'Declined'), ('FAILED', 'Failed'), ('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('SETTLED', 'Settled')], default='PENDING', max_length=100)),
                ('method', models.CharField(choices=[('BLIK', 'blik'), ('CARD', 'card')], max_length=100)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='payment', to='shopping.orderdetails')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
